version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "DISABLE_SECURITY_PLUGIN=true" # Disables Security plugin
      - path.repo=/usr/share/opensearch/snapshots
      #- OPENSEARCH_INITIAL_ADMIN_PASSWORD=QL/87z8£ZW&4   # Sets the demo admin user password when using demo configuration, required for OpenSearch 2.12 and later
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - repo:/usr/share/opensearch/snapshots
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net
    user: root
    command: >
      /bin/bash -c "
        chown -R opensearch:opensearch /usr/share/opensearch/snapshots &&
        chmod -R 777 /usr/share/opensearch/snapshots &&
        yum install util-linux -y &&
        su opensearch -c './opensearch-docker-entrypoint.sh opensearch'
      "
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    volumes:
      - ./opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    networks:
      - opensearch-net
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://opensearch:9200
      - SELF_TRACING_ENABLED=true
      - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      - "9411:9411"
    networks:
      - opensearch-net
    depends_on:
      - opensearch
    command: --logging.level.zipkin2=DEBUG

volumes:
  opensearch-data1:
  repo:

networks:
  opensearch-net:


