version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - path.repo=/usr/share/elasticsearch/snapshots
    volumes:
      - data:/usr/share/elasticsearch/data
      - repo:/usr/share/elasticsearch/snapshots
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    user: root
    command: >
      /bin/bash -c "
        chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/snapshots &&
        chmod -R 777 /usr/share/elasticsearch/snapshots &&
        su elasticsearch -c '/usr/local/bin/docker-entrypoint.sh eswrapper'
      "

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsearch:9200
      - SELF_TRACING_ENABLED=true
      - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      - "9411:9411"
    networks:
      - elastic
    depends_on:
      - elasticsearch
    command: --logging.level.zipkin2=DEBUG

volumes:
  data:
    driver: local
  repo:
    driver: local

networks:
  elastic:
    driver: bridge
